<?php

$config = [
//    'nextActive' => '<li><a href="{{url}}"><i class="glyphicon glyphicon-chevron-right"></i></a></li>',
//    'nextDisabled' => '<li><a><i class="glyphicon glyphicon-chevron-right"></i></a></li>',
//    'prevActive' => '<li><a href="{{url}}"><i class="glyphicon glyphicon-chevron-left"></i></a></li>',
//    'prevDisabled' => '<li><a><i class="glyphicon glyphicon-chevron-left"></i></a></li>',
    'counterRange' => 'Exibindo de {{start}} a {{end}} de {{count}} registros',
    'counterPages' => 'Exibindo de {{start}} a {{end}} de {{count}} registros',
//    'counterPages' => 'Exibindo {{page}} de {{pages}}',
    'nextActive'   => '<li class="page-item"><a class="page-link" href="{{url}}" aria-label="Next"><span aria-hidden="true">»</span><span class="sr-only">Next</span></a></li>',
    'nextDisabled' => '<li class="page-item disabled"><a class="page-link" href="{{url}}" aria-label="Next"><span aria-hidden="true">»</span><span class="sr-only">Next</span></a></li>',
    'prevActive'   => '<li class="page-item"><a class="page-link" href="{{url}}" aria-label="Previous"><span aria-hidden="true">«</span><span class="sr-only">Previous</span></a></li>',
    'prevDisabled' => '<li class="page-item disabled"><a class="page-link" href="{{url}}" aria-label="Previous"><span aria-hidden="true">«</span><span class="sr-only">Previous</span></a></li>',
    // 'first' => '<li class="first"><a href="{{url}}">{{text}}</a></li>',
    //'last' => '<li class="last"><a href="{{url}}">{{text}}</a></li>',
    'number'       => '<li class="page-item"><a class="page-link" href="{{url}}">{{text}}</a></li>',
    //'number' => '<a class="btn btn-white" href="{{url}}">{{text}}</a>',
    //'current' => '<a class="btn btn-white active" href="{{url}}">{{text}}</a>',
    'current'      => '<li class="page-item active"><a class="page-link" href="{{url}}">{{text}}<span class="sr-only">(current)</span></a></li>',
//    'ellipsis' => '<li class="ellipsis">...</li>',
//    'sort' => '<a href="{{url}}">{{text}}</a>',
//    'sortAsc' => '<a class="asc" href="{{url}}">{{text}}</a>',
//    'sortDesc' => '<a class="desc" href="{{url}}">{{text}}</a>',
//    'sortAscLocked' => '<a class="asc locked" href="{{url}}">{{text}}</a>',
//    'sortDescLocked' => '<a class="desc locked" href="{{url}}">{{text}}</a>',
];
